server:
  port: 8080
spring:
  redis:
      host: 127.0.0.1
      port: 6379
      password: 123
      jedis:
        pool:
          min-idle: 8
          max-idle: 500
          max-active: 2000
          max-wait: 1000ms
      timeout: 2000ms
      database: 1

